name: lxi-tools-win64-build-downgrade-packs-check
on: [push, workflow_dispatch]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-check:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git
      - name: Build
        run: |
          bash msys2_scripts/msys2-lxi-tools-pacman.sh
          bash msys2_scripts/msys2-lxi-tools-downgrade_packs.sh
          LXI_TAG="$(cd lxi-tools && git describe --tags)"
          LIBLXI_TAG="$(cd liblxi && git describe --tags)"
          FULL_TAG=$LXI_TAG-$LIBLXI_TAG
          cd lxi-tools && meson rewrite kwargs set project / version $FULL_TAG && cd ..
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-imagemagick
          meson setup liblxi/build liblxi
          meson compile -C liblxi/build
          meson install -C liblxi/build
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/ucrt64/lib/pkgconfig:$PKG_CONFIG_PATH
          export PATH=$PATH:/ucrt64/bin/
          meson setup lxi-tools/build lxi-tools
          export BUILD_VERSION=$(shell meson introspect --projectinfo lxi-tools/build | /ucrt64/bin/jq -r '.version')
          meson compile -j 1 -C lxi-tools/build
          pacman -Rsc --noconfirm mingw-w64-ucrt-x86_64-imagemagick mingw-w64-ucrt-x86_64-jq
          bash msys2_scripts/msys2-lxi-tools-redistributable.sh
          export APP_DATA=usr
          /ucrt64/bin/makensis msys2_scripts/nsis_lxi-toolst.nsi
          echo $BUILD_VERSION > release_tag.txt
          cat release_tag.txt 
          mv msys2_scripts/lxi-tools-$BUILD_VERSION.exe lxi-tools.exe
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lxi-tools.exe
          path: lxi-tools.exe
